cache:
  yarn: true
  directories:
  - node_modules

script:
- yarn install
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  on:
    branch: master
